base-package: com.jswl.jwtservice
server:
  port: 8011

mybatis-plus:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      field-strategy: default
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: ${base-package}.entity
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8
    username: root
    password: root

